/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.jax.mvar.insert

class App {

    static void main(String[] args) {
        VcfFileInsertionService insertService = new VcfFileInsertionService();

        String folderPath;
        int batchSize = -1;
        if (args != null && args.length == 1) {
            folderPath = args[0];
        } else if (args != null && args.length == 2) {
            folderPath = args[0];
            batchSize = Integer.parseInt(args[1]);
        } else {
            return;
        }
        try {
            File f = new File(folderPath);
            assert f != null;
            if (f.isDirectory()) {
                File[] files = new File(folderPath).listFiles();
                assert files != null;
                for (File file : files) {
                    if (file.isFile() && (file.getName().endsWith(".gz") || (file.getName().endsWith(".vcf"))))
                        insertService.loadVCF(file, batchSize);
                }
            } else if (f.isFile()) {
                insertService.loadVCF(f, batchSize);
            }
        } catch(Exception exc) {
            System.out.println(Arrays.toString(exc.getStackTrace()));
        }

    }
}
